# Generated by Django 4.2.9 on 2024-01-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirm',
            old_name='cose',
            new_name='code',
        ),
    ]
